/* Generated by scripts/generate-exporter-mapper.py — do not edit by hand. */
window.RADIOMAP_EXPORTERS = [
  { id: 'chirp', label: 'CHIRP', fn: 'exportChirp', url: 'https://chirpmyradio.com/' },
  { id: 'ft5dr', label: 'Yaesu FT5DR', fn: 'exportFT5DR', url: 'https://www.yaesu.com' }
];
