/**
 * Yaesu FT5DR ADMS CSV exporter for Radiomap repeater data.
 * Generated by scripts/generate-exporter-mapper.py — do not edit by hand.
 * Format: Yaesu ADMS-1 compatible CSV — no header row, 54 columns per row.
 *
 * Column layout (inferred from reference.csv):
 *   0:channel  1:skip  2:rx_freq  3:tx_freq  4:offset(|tx-rx|)  5:OFF  6:ON
 *   7:tx_mode  8:rx_mode  9:ON  10:name  11:tone_mode  12:ctcss_freq
 *   13:dcs_code  14:dcs_polarity  15:1600Hz  16:rx_squelch  17:tx_squelch
 *   18:power  19:OFF  20:ON  21:step  22-51:feature_flags  52:empty  53:0
 *
 * Exposes:
 *   exportFT5DR(rows, criteria)  — triggers browser download
 *   buildFT5DRFilename(criteria) — returns filename string
 */

function buildFT5DRFilename(criteria) {
  var date = new Date().toISOString().slice(0, 10);
  var parts = ['radiomap', 'ft5dr'];
  var sanitize = function (s) {
    return String(s).replace(/\s+/g, '-').replace(/[^a-zA-Z0-9\-\u00e1\u00e9\u00ed\u00f3\u00fa\u00f1]/g, '').toLowerCase().slice(0, 30);
  };
  if (criteria) {
    if (criteria.context === 'neighbors') {
      parts.push('nodos-cercanos');
      if (criteria.signal) parts.push(sanitize(criteria.signal));
    }
    if (criteria.nearMe) parts.push('cerca-de-mi');
    var bandas = criteria.bandas || (criteria.banda ? [criteria.banda] : []);
    bandas.forEach(function (b) { if (b) parts.push(String(b).toLowerCase()); });
    var types = criteria.types || [];
    if (types.indexOf('echolink') >= 0) parts.push('echolink');
    if (types.indexOf('dmr') >= 0) parts.push('dmr');
    if (types.indexOf('radioclub') >= 0) parts.push('radioclubes');
    if (types.indexOf('atc') >= 0) parts.push('atc');
    if (types.indexOf('fire') >= 0) parts.push('bomberos');
    if (types.indexOf('ambulance') >= 0) parts.push('ambulancia');
    if (types.indexOf('sea') >= 0) parts.push('maritimo');
    var conferences = criteria.conferences || (criteria.echoLinkConference ? [criteria.echoLinkConference] : []);
    conferences.forEach(function (c) { if (c) parts.push('conferencia-' + sanitize(c)); });
    var regions = criteria.regions || (criteria.region ? [criteria.region] : []);
    regions.forEach(function (reg) { var r = sanitize(reg); if (r) parts.push('region-' + r); });
    var search = criteria.search != null ? criteria.search : '';
    if (search && String(search).trim()) {
      var q = sanitize(String(search).trim()).slice(0, 20);
      if (q) parts.push('busqueda-' + q);
    }
  }
  parts.push(date);
  return parts.join('-') + '.csv';
}

function exportFT5DR(rows, criteria) {
  var esc = function (v) {
    if (v == null || v === '') return '';
    var s = '' + v;
    if (s.indexOf(',') >= 0 || s.indexOf('"') >= 0 || s.indexOf('\n') >= 0) {
      return '"' + s.replace(/"/g, '""') + '"';
    }
    return s;
  };

  var mapMode = function (banda) {
    if (!banda) return 'FM';
    var b = String(banda).toUpperCase();
    if (b.indexOf('/AM') >= 0 || b.indexOf('ATC') >= 0) return 'AM';
    return 'FM';
  };

  /* Yaesu FT5DR supported bands: VHF 108-174 MHz, UHF 420-470 MHz */
  var inSupportedBand = function (f) {
    return (f >= 108 && f <= 174) || (f >= 420 && f <= 470);
  };

  /* Standard CTCSS tones (EIA) */
  var CTCSS = [67.0,71.9,74.4,77.0,79.7,82.5,85.4,88.5,91.5,94.8,97.4,
    100.0,103.5,107.2,110.9,114.8,118.8,123.0,127.3,131.8,136.5,141.3,
    146.2,151.4,156.7,162.2,167.9,173.8,179.9,186.2,192.8,203.5,210.7,
    218.1,225.7,233.6,241.8,250.3];

  var flags = [];
  for (var i = 0; i < 30; i++) flags.push('OFF');

  var channel = 1;
  var dataRows = rows.map(function (r) {
    if (r.isDMR === true || r.isDMR === 'true' || r.isDMR === '1' ||
        (r.banda && String(r.banda).toUpperCase().indexOf('DMR') >= 0)) {
      return null;
    }

    var rx = parseFloat(r.rx);
    var txRaw = parseFloat(r.tx);
    var rxOk = !isNaN(rx);
    var tx = !isNaN(txRaw) ? txRaw : rx;

    if (!rxOk || !inSupportedBand(rx)) return null;
    if (Math.round(rx * 1000) % 5 !== 0) return null;

    var tonoRaw = r.tono != null ? String(r.tono).trim() : '';
    var tonoNum = parseFloat(tonoRaw);
    var isValidTone = !isNaN(tonoNum) && CTCSS.some(function(t) { return Math.abs(t - tonoNum) < 0.05; });
    var hasTone = tonoRaw !== '' && isValidTone;
    var toneMode = hasTone ? 'TONE' : 'OFF';
    var ctcssFreq = hasTone ? tonoNum.toFixed(1) + ' Hz' : '88.5 Hz';

    var mode = mapMode(r.banda);
    var isAM = mode === 'AM';

    var normalizeText = function (s) {
      return String(s)
        .replace(/[áÁ]/g, 'A').replace(/[éÉ]/g, 'E')
        .replace(/[íÍ]/g, 'I').replace(/[óÓ]/g, 'O')
        .replace(/[úÚ]/g, 'U').replace(/[ñÑ]/g, 'N')
        .toUpperCase();
    };

    var name = r.signal != null ? normalizeText(String(r.signal)).slice(0, 16) : '';
    var comment = r.nombre != null ? normalizeText(String(r.nombre)) : '';

    var offset = rxOk ? parseFloat(Math.abs(tx - rx).toFixed(6)).toString() : '0';

    var fmtFreq = function (f) { return parseFloat(f.toFixed(6)).toString(); };

    var cols = [
      channel++,
      'OFF',
      rxOk ? fmtFreq(rx) : '',
      rxOk ? fmtFreq(tx) : '',
      offset,
      rxOk ? (tx > rx ? '+RPT' : tx < rx ? '-RPT' : 'OFF') : 'OFF',
      'ON',
      mode,
      mode,
      'ON',
      esc(name),
      toneMode,
      ctcssFreq,
      '023',
      'RX Normal TX Normal',
      '1600 Hz',
      isAM ? '-' : 'RX 00',
      isAM ? '-' : 'TX 00',
      'L2 (1W)',
      'OFF',
      'ON',
      '12.5KHz'
    ].concat(flags).concat([esc(comment), 0]);
    return cols.join(',');
  }).filter(function (line) { return line !== null; });

  while (dataRows.length < 900) {
    var ch = dataRows.length + 1;
    var emptyRow = new Array(54).fill('');
    emptyRow[0] = ch;
    emptyRow[53] = 0;
    dataRows.push(emptyRow.join(','));
  }

  /* No header row — Yaesu ADMS format starts directly with data, fixed 899 rows */
  var csv = dataRows.join('\r\n');
  var blob = new Blob([csv], { type: 'text/csv;charset=utf-8' });
  var a = document.createElement('a');
  a.href = URL.createObjectURL(blob);
  a.download = buildFT5DRFilename(criteria);
  a.click();
  URL.revokeObjectURL(a.href);
}
