/**
 * Yaesu FTM-150 ADMS CSV exporter for Radiomap repeater data.
 * Generated by scripts/generate-exporter-mapper.py — do not edit by hand.
 * Format: Yaesu ADMS compatible CSV — no header row, 19 columns per row.
 *
 * Column layout (from reference.csv):
 *   0:channel  1:rx_freq  2:tx_freq  3:offset(|tx-rx|)  4:offset_dir
 *   5:mode  6:name(8)  7:tone_mode  8:ctcss_freq  9:dcs_code
 *   10:bell  11:power  12:pager  13:bclo  14:step
 *   15:att  16:squelch  17:comment  18:0
 *
 * Exposes:
 *   exportFTM150(rows, criteria)  — triggers browser download
 *   buildFTM150Filename(criteria) — returns filename string
 */

function buildFTM150Filename(criteria) {
  var date = new Date().toISOString().slice(0, 10);
  var parts = ['radiomap', 'ftm150'];
  var sanitize = function (s) {
    return String(s).replace(/\s+/g, '-').replace(/[^a-zA-Z0-9\-\u00e1\u00e9\u00ed\u00f3\u00fa\u00f1]/g, '').toLowerCase().slice(0, 30);
  };
  if (criteria) {
    if (criteria.context === 'neighbors') {
      parts.push('nodos-cercanos');
      if (criteria.signal) parts.push(sanitize(criteria.signal));
    }
    if (criteria.nearMe) parts.push('cerca-de-mi');
    var bandas = criteria.bandas || (criteria.banda ? [criteria.banda] : []);
    bandas.forEach(function (b) { if (b) parts.push(String(b).toLowerCase()); });
    var types = criteria.types || [];
    if (types.indexOf('echolink') >= 0) parts.push('echolink');
    if (types.indexOf('dmr') >= 0) parts.push('dmr');
    if (types.indexOf('radioclub') >= 0) parts.push('radioclubes');
    if (types.indexOf('atc') >= 0) parts.push('atc');
    if (types.indexOf('fire') >= 0) parts.push('bomberos');
    if (types.indexOf('ambulance') >= 0) parts.push('ambulancia');
    if (types.indexOf('sea') >= 0) parts.push('maritimo');
    var conferences = criteria.conferences || (criteria.echoLinkConference ? [criteria.echoLinkConference] : []);
    conferences.forEach(function (c) { if (c) parts.push('conferencia-' + sanitize(c)); });
    var regions = criteria.regions || (criteria.region ? [criteria.region] : []);
    regions.forEach(function (reg) { var r = sanitize(reg); if (r) parts.push('region-' + r); });
    var search = criteria.search != null ? criteria.search : '';
    if (search && String(search).trim()) {
      var q = sanitize(String(search).trim()).slice(0, 20);
      if (q) parts.push('busqueda-' + q);
    }
  }
  parts.push(date);
  return parts.join('-') + '.csv';
}

function exportFTM150(rows, criteria) {
  var esc = function (v) {
    if (v == null || v === '') return '';
    var s = '' + v;
    if (s.indexOf(',') >= 0 || s.indexOf('"') >= 0 || s.indexOf('\n') >= 0) {
      return '"' + s.replace(/"/g, '""') + '"';
    }
    return s;
  };

  var mapMode = function (banda) {
    if (!banda) return 'FM';
    var b = String(banda).toUpperCase();
    if (b.indexOf('/AM') >= 0 || b.indexOf('ATC') >= 0) return 'AM';
    return 'FM';
  };

  /* Yaesu FTM-150 supported bands: VHF 108-174 MHz, UHF 420-470 MHz */
  var inSupportedBand = function (f) {
    return (f >= 108 && f <= 174) || (f >= 420 && f <= 470);
  };

  /* Standard CTCSS tones (EIA) */
  var CTCSS = [67.0,71.9,74.4,77.0,79.7,82.5,85.4,88.5,91.5,94.8,97.4,
    100.0,103.5,107.2,110.9,114.8,118.8,123.0,127.3,131.8,136.5,141.3,
    146.2,151.4,156.7,162.2,167.9,173.8,179.9,186.2,192.8,203.5,210.7,
    218.1,225.7,233.6,241.8,250.3];

  var normalizeText = function (s) {
    return String(s)
      .replace(/[áÁ]/g, 'A').replace(/[éÉ]/g, 'E')
      .replace(/[íÍ]/g, 'I').replace(/[óÓ]/g, 'O')
      .replace(/[úÚ]/g, 'U').replace(/[ñÑ]/g, 'N')
      .toUpperCase();
  };

  var channel = 1;
  var dataRows = rows.map(function (r) {
    if (r.isDMR === true || r.isDMR === 'true' || r.isDMR === '1' ||
        (r.banda && String(r.banda).toUpperCase().indexOf('DMR') >= 0)) {
      return null;
    }

    var rx = parseFloat(r.rx);
    var txRaw = parseFloat(r.tx);
    var rxOk = !isNaN(rx);
    var tx = !isNaN(txRaw) ? txRaw : rx;

    if (!rxOk || !inSupportedBand(rx)) return null;
    if (Math.round(rx * 1000) % 5 !== 0) return null;

    var tonoRaw = r.tono != null ? String(r.tono).trim() : '';
    var tonoNum = parseFloat(tonoRaw);
    var isValidTone = !isNaN(tonoNum) && CTCSS.some(function(t) { return Math.abs(t - tonoNum) < 0.05; });
    var hasTone = tonoRaw !== '' && isValidTone;
    var toneMode = hasTone ? 'TONE' : 'OFF';
    var ctcssFreq = hasTone ? tonoNum.toFixed(1) + ' Hz' : '100.0 Hz';

    var mode = mapMode(r.banda);

    var name = r.signal != null ? normalizeText(String(r.signal)).slice(0, 8) : '';
    var comment = r.nombre != null ? normalizeText(String(r.nombre)) : '';

    var fmtFreq = function (f) { return parseFloat(f.toFixed(5)).toString(); };
    var offset = parseFloat(Math.abs(tx - rx).toFixed(2)).toString();
    var offsetDir = rxOk ? (tx > rx ? '+RPT' : tx < rx ? '-RPT' : 'OFF') : 'OFF';
    var step = rx < 300 ? '5.0KHz' : '25.0KHz';

    var cols = [
      channel++,
      rxOk ? fmtFreq(rx) : '',
      rxOk ? fmtFreq(tx) : '',
      offset,
      offsetDir,
      mode,
      esc(name),
      toneMode,
      ctcssFreq,
      '023',
      '1500 Hz',
      'HIGH',
      'OFF',
      'YES',
      step,
      'OFF',
      'OFF',
      esc(comment),
      0
    ];
    return cols.join(',');
  }).filter(function (line) { return line !== null; });

  while (dataRows.length < 1000) {
    var ch = dataRows.length + 1;
    var emptyRow = new Array(19).fill('');
    emptyRow[0] = ch;
    emptyRow[18] = 0;
    dataRows.push(emptyRow.join(','));
  }

  /* No header row — Yaesu ADMS format starts directly with data, fixed 1000 rows */
  var csv = dataRows.join('\r\n');
  var blob = new Blob([csv], { type: 'text/csv;charset=utf-8' });
  var a = document.createElement('a');
  a.href = URL.createObjectURL(blob);
  a.download = buildFTM150Filename(criteria);
  a.click();
  URL.revokeObjectURL(a.href);
}
