/**
 * CHIRP CSV exporter for Radiomap repeater data.
 * Generated by scripts/generate-exporter-mapper.py — do not edit by hand.
 * CHIRP columns: Location,Name,Frequency,Duplex,Offset,Tone,rToneFreq,cToneFreq,DtcsCode,DtcsPolarity,RxDtcsCode,CrossMode,Mode,TStep,Skip,Power,Comment,URCALL,RPT1CALL,RPT2CALL,DVCODE
 *
 * Exposes:
 *   exportChirp(rows, criteria)  — triggers browser download of CHIRP CSV
 *   buildChirpFilename(criteria) — returns filename string
 */

function buildChirpFilename(criteria) {
  var date = new Date().toISOString().slice(0, 10);
  var parts = ['radiomap', 'chirp'];
  var sanitize = function (s) {
    return String(s).replace(/\s+/g, '-').replace(/[^a-zA-Z0-9\-\u00e1\u00e9\u00ed\u00f3\u00fa\u00f1]/g, '').toLowerCase().slice(0, 30);
  };
  if (criteria) {
    if (criteria.context === 'neighbors') {
      parts.push('nodos-cercanos');
      if (criteria.signal) parts.push(sanitize(criteria.signal));
    }
    if (criteria.nearMe) parts.push('cerca-de-mi');
    var bandas = criteria.bandas || (criteria.banda ? [criteria.banda] : []);
    bandas.forEach(function (b) { if (b) parts.push(String(b).toLowerCase()); });
    var types = criteria.types || [];
    if (types.indexOf('echolink') >= 0) parts.push('echolink');
    if (types.indexOf('dmr') >= 0) parts.push('dmr');
    if (types.indexOf('radioclub') >= 0) parts.push('radioclubes');
    if (types.indexOf('atc') >= 0) parts.push('atc');
    if (types.indexOf('fire') >= 0) parts.push('bomberos');
    if (types.indexOf('ambulance') >= 0) parts.push('ambulancia');
    if (types.indexOf('sea') >= 0) parts.push('maritimo');
    var conferences = criteria.conferences || (criteria.echoLinkConference ? [criteria.echoLinkConference] : []);
    conferences.forEach(function (c) { if (c) parts.push('conferencia-' + sanitize(c)); });
    var regions = criteria.regions || (criteria.region ? [criteria.region] : []);
    regions.forEach(function (reg) { var r = sanitize(reg); if (r) parts.push('region-' + r); });
    var search = criteria.search != null ? criteria.search : '';
    if (search && String(search).trim()) {
      var q = sanitize(String(search).trim()).slice(0, 20);
      if (q) parts.push('busqueda-' + q);
    }
  }
  parts.push(date);
  return parts.join('-') + '.csv';
}

function exportChirp(rows, criteria) {
  var HEADER = 'Location,Name,Frequency,Duplex,Offset,Tone,rToneFreq,cToneFreq,DtcsCode,DtcsPolarity,RxDtcsCode,CrossMode,Mode,TStep,Skip,Power,Comment,URCALL,RPT1CALL,RPT2CALL,DVCODE';

  var esc = function (v) {
    if (v == null || v === '') return '';
    var s = '' + v;
    if (s.indexOf(',') >= 0 || s.indexOf('"') >= 0 || s.indexOf('\n') >= 0) {
      return '"' + s.replace(/"/g, '""') + '"';
    }
    return s;
  };

  var mapMode = function (banda) {
    if (!banda) return 'FM';
    var b = String(banda).toUpperCase();
    if (b.indexOf('DMR') >= 0) return 'DMR';
    if (b.indexOf('/AM') >= 0 || b.indexOf('ATC') >= 0) return 'AM';
    return 'FM';
  };

  var location = 1;
  var dataRows = rows.map(function (r) {
    if (r.isDMR === true || r.isDMR === 'true' || r.isDMR === '1' ||
        (r.banda && String(r.banda).toUpperCase().indexOf('DMR') >= 0)) {
      return null;
    }

    var rx = parseFloat(r.rx);
    var tx = parseFloat(r.tx);
    var rxOk = !isNaN(rx);
    var txOk = !isNaN(tx);

    var duplex = '';
    var offset = (0).toFixed(6);
    if (rxOk && txOk) {
      var diff = tx - rx;
      if (Math.abs(diff) > 0.0001) {
        duplex = diff > 0 ? '+' : '-';
        offset = Math.abs(diff).toFixed(6);
      }
    }

    var tonoRaw = r.tono != null ? String(r.tono).trim() : '';
    var tonoNum = parseFloat(tonoRaw);
    var hasTone = tonoRaw !== '' && !isNaN(tonoNum) && tonoNum > 0;
    var toneField = hasTone ? 'Tone' : '';
    var rToneFreq = hasTone ? tonoNum.toFixed(1) : '88.5';

    var nombre = r.nombre != null ? String(r.nombre) : '';
    var ubicacion = r.ubicacion != null ? String(r.ubicacion) : '';
    var comment = '';
    if (nombre && ubicacion) {
      comment = (nombre + ' - ' + ubicacion).slice(0, 255);
    } else if (nombre) {
      comment = nombre.slice(0, 255);
    } else if (ubicacion) {
      comment = ubicacion.slice(0, 255);
    }

    var name = r.signal != null ? String(r.signal).slice(0, 16) : '';

    var cols = [
      location++,
      esc(name),
      rxOk ? rx.toFixed(6) : '',
      duplex,
      offset,
      toneField,
      rToneFreq,
      rToneFreq,
      '023',
      'NN',
      '023',
      'Tone->Tone',
      mapMode(r.banda),
      '12.50',
      '',
      '1W',
      esc(comment),
      '',
      '',
      '',
      ''
    ];
    return cols.join(',');
  }).filter(function (line) { return line !== null; });

  var csv = [HEADER].concat(dataRows).join('\r\n');
  var blob = new Blob([csv], { type: 'text/csv;charset=utf-8' });
  var a = document.createElement('a');
  a.href = URL.createObjectURL(blob);
  a.download = buildChirpFilename(criteria);
  a.click();
  URL.revokeObjectURL(a.href);
}
